name: OWASP Dependency-Check

on:
  workflow_dispatch: # Allows manual execution
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run OWASP Dependency-Check
        uses: dependency-check/dependency-check_Action@master
        with:
          project: "dvja"
          path: "."
          format: "HTML"
          out: "reports"

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html
